stages:
  - Build container
  - Sanity Checks
  - Build benchmark container
  - Run tests
  - Deploy
  - Cleanup
  - Benchmark
variables:
  REBENCH_OPTIONS: "-df $CI_PROJECT_DIR/benchmarks.data -R"
  REBENCH_RUN: "/opt/rbenchmarking/Setup/run.sh /opt/rbenchmarking/rebench.conf /opt/rbenchmarking/Benchmarks /opt/rir/build/release"
  REBENCH_RUN_BL: "/opt/rbenchmarking/Setup/run.sh /opt/rbenchmarking/rebench.conf /opt/rbenchmarking/Benchmarks . /opt/rir/external/custom-r /opt/graal"

sanity:
  image: registry.gitlab.com/rirvm/rir_mirror:$CI_COMMIT_SHA
  variables:
    GIT_STRATEGY: none
    PIR_LLVM_OPT_LEVEL: 1
  stage: Sanity Checks
  needs:
    - rir_container
  script:
    - /opt/rir/tools/cppcheck
    - /opt/rir/build/release/bin/tests

rir_container:
  stage: Build container
  image: docker:stable
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:19.03.0-dind
  before_script:
    - docker info
  script:
    - echo "$CI_BUILD_TOKEN" | docker login -u "$CI_BUILD_USER" --password-stdin registry.gitlab.com
    - docker build --build-arg CI_COMMIT_SHA=$CI_COMMIT_SHA -t registry.gitlab.com/rirvm/rir_mirror:$CI_COMMIT_SHA .
    - docker push registry.gitlab.com/rirvm/rir_mirror:$CI_COMMIT_SHA
  tags:
    - dockerInDocker

benchmark_container:
  stage: Build benchmark container
  needs:
    - rir_container
  image: docker:stable
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:19.03.0-dind
  before_script:
    - docker info
  tags:
    - dockerInDocker
  script:
    - echo "$CI_BUILD_TOKEN" | docker login -u "$CI_BUILD_USER" --password-stdin registry.gitlab.com
    - cd container/benchmark
    - docker build --build-arg CI_COMMIT_SHA=$CI_COMMIT_SHA -t registry.gitlab.com/rirvm/rir_mirror/benchmark:$CI_COMMIT_SHA .
    - docker push registry.gitlab.com/rirvm/rir_mirror/benchmark:$CI_COMMIT_SHA

# Run check-all in release mode  (additionally check pir types)
test_release_1:
  image: registry.gitlab.com/rirvm/rir_mirror:$CI_COMMIT_SHA
  variables:
    GIT_STRATEGY: none
    PIR_INLINER_INLINE_UNLIKELY: 1
    PIR_MAX_INPUT_SIZE: 10000
    PIR_INLINER_MAX_SIZE: 10000
  stage: Run tests
  needs:
    - sanity
  except:
    - schedules
  script:
    - cd /opt/rir/build/release
    - RIR_CHECK_PIR_TYPES=1 bin/tests
    - RIR_CHECK_PIR_TYPES=1 bin/gnur-make-tests check-devel
    - ../../tools/check-gnur-make-tests-error
  artifacts:
    paths:
    - ../../external/custom-r/tests/*/*check.log
    when: on_failure
    expire_in: 1 week

test_release_2:
  image: registry.gitlab.com/rirvm/rir_mirror:$CI_COMMIT_SHA
  variables:
    GIT_STRATEGY: none
    PIR_INLINER_INLINE_UNLIKELY: 1
    PIR_MAX_INPUT_SIZE: 10000
    PIR_INLINER_MAX_SIZE: 10000
  stage: Run tests
  needs:
    - sanity
  except:
    - schedules
  script:
    - cd /opt/rir/build/release
    - bin/gnur-make-tests check-recommended
    - ../../tools/check-gnur-make-tests-error
  artifacts:
    paths:
    - ../../external/custom-r/tests/*/*check.log
    when: on_failure
    expire_in: 1 week

# Run some tests in the debug mode
tests_debug:
  image: registry.gitlab.com/rirvm/rir_mirror:$CI_COMMIT_SHA
  variables:
    GIT_STRATEGY: none
  stage: Run tests
  needs:
    - sanity
  except:
    - schedules
  script:
    - cd /opt/rir/build/debugopt
    - export UNSOUND_OPTS=off
    - R_ENABLE_JIT=0 ./bin/tests
    - R_ENABLE_JIT=1 ./bin/tests
    - R_ENABLE_JIT=2 ./bin/tests
    - R_ENABLE_JIT=3 ./bin/tests
    - PIR_ENABLE=off ./bin/tests
    - PIR_ENABLE=force ./bin/tests
    - ./bin/gnur-make-tests check-devel
    - ../../tools/check-gnur-make-tests-error
  artifacts:
    paths:
    - ../../external/custom-r/tests/*/*check.log
    when: on_failure
    expire_in: 1 week

# Run some tests in the full verify (release) mode
tests_fullverify:
  image: registry.gitlab.com/rirvm/rir_mirror:$CI_COMMIT_SHA
  variables:
    GIT_STRATEGY: none
    PIR_MAX_INPUT_SIZE: 10000
    PIR_INLINER_MAX_SIZE: 10000
  stage: Run tests
  needs:
    - sanity
  except:
    - schedules
  script:
    - cd /opt/rir/build/fullverifier
    - bin/tests
    - bin/gnur-make-tests check-devel
    - ../../tools/check-gnur-make-tests-error
  artifacts:
    paths:
    - ../../external/custom-r/tests/*/*check.log
    when: on_failure
    expire_in: 1 week

# Test particular features, like deoptimization and serialization
test_features_1:
  image: registry.gitlab.com/rirvm/rir_mirror:$CI_COMMIT_SHA
  variables:
    GIT_STRATEGY: none
    PIR_LLVM_OPT_LEVEL: 0
  stage: Run tests
  needs:
    - sanity
  except:
    - schedules
  script:
    - cd /opt/rir/build/debugopt
#    - PIR_ENABLE_PROFILER=1 ./bin/tests
    - cd /opt/rir/build/release
    - PIR_DEOPT_CHAOS=1000 PIR_INLINER_MAX_INLINEE_SIZE=800 bin/gnur-make-tests check
    - PIR_WARMUP=2 PIR_DEOPT_CHAOS=400 ./bin/gnur-make-tests check
    - RIR_SERIALIZE_CHAOS=1 FAST_TESTS=1 ./bin/tests
    - PIR_GLOBAL_SPECIALIZATION_LEVEL=0 ./bin/tests
    - PIR_GLOBAL_SPECIALIZATION_LEVEL=1 ./bin/tests
    - PIR_GLOBAL_SPECIALIZATION_LEVEL=2 ./bin/tests
    - PIR_GLOBAL_SPECIALIZATION_LEVEL=3 ./bin/tests
    - PIR_GLOBAL_SPECIALIZATION_LEVEL=4 ./bin/tests
    - PIR_GLOBAL_SPECIALIZATION_LEVEL=5 ./bin/tests

test_features_2:
  image: registry.gitlab.com/rirvm/rir_mirror:$CI_COMMIT_SHA
  variables:
    GIT_STRATEGY: none
    PIR_LLVM_OPT_LEVEL: 1
  stage: Run tests
  needs:
    - sanity
  except:
    - schedules
  script:
    - cd /opt/rir/build/release
    - ./bin/gnur-make-tests check

# Run ubsan and gc torture
test_sanitize1:
  image: registry.gitlab.com/rirvm/rir_mirror:$CI_COMMIT_SHA
  variables:
    GIT_STRATEGY: none
    PIR_MAX_INPUT_SIZE: 10000
    PIR_INLINER_MAX_SIZE: 10000
    PIR_LLVM_OPT_LEVEL: 0
  stage: Run tests
  needs:
    - sanity
  except:
    - schedules
  script:
    - cd /opt/rir/build/sanitize
    - ENABLE_VALGRIND=1 ./bin/tests
    - R_GCTORTURE=1000 bin/tests

# Run ubsan and gc torture
test_sanitize2:
  image: registry.gitlab.com/rirvm/rir_mirror:$CI_COMMIT_SHA
  variables:
    GIT_STRATEGY: none
  stage: Run tests
  needs:
    - sanity
  except:
    - schedules
  script:
    - cd /opt/rir/build/sanitize
    - R_GCTORTURE=20000 ./bin/gnur-make-tests check

# Test with inlining big functions
test_big_inline:
  image: registry.gitlab.com/rirvm/rir_mirror:$CI_COMMIT_SHA
  variables:
    GIT_STRATEGY: none
    PIR_MAX_INPUT_SIZE: 10000
    PIR_INLINER_MAX_SIZE: 10000
    PIR_LLVM_OPT_LEVEL: 0
  stage: Run tests
  needs:
    - sanity
  except:
    - schedules
  script:
    - cd /opt/rir/build/release
    - PIR_INLINER_MAX_INLINEE_SIZE=2000 ./bin/tests
    - PIR_INLINER_MAX_INLINEE_SIZE=1500 PIR_DEOPT_CHAOS=100 ./bin/tests
    - PIR_INLINER_MAX_INLINEE_SIZE=1500 PIR_DEOPT_CHAOS=1000 ./bin/tests
    - PIR_INLINER_MAX_INLINEE_SIZE=400 PIR_INLINER_INLINE_UNLIKELY=1 ./bin/gnur-make-tests check

# Test the benchmarks container before deploying
test_benchmarks:
  image: registry.gitlab.com/rirvm/rir_mirror/benchmark:$CI_COMMIT_SHA
  variables:
    GIT_STRATEGY: none
  stage: Run tests
  needs:
    - benchmark_container
  script:
    - PIR_ENABLE=0 PATH=~/.local/bin:$PATH /opt/rbenchmarking/Setup/run.sh /opt/rbenchmarking/rebench.conf /opt/rbenchmarking/Benchmarks /opt/rir/build/release/ /opt/rir/external/custom-r "e:RIR-LLVM -R -r --iterations 2"
    - PIR_DEOPT_CHAOS=200 PATH=~/.local/bin:$PATH /opt/rbenchmarking/Setup/run.sh /opt/rbenchmarking/rebench.conf /opt/rbenchmarking/Benchmarks /opt/rir/build/release/ /opt/rir/external/custom-r "e:PIR-LLVM -R -r --iterations 2"
    - PATH=~/.local/bin:$PATH /opt/rbenchmarking/Setup/run.sh /opt/rbenchmarking/rebench.conf /opt/rbenchmarking/Benchmarks /opt/rir/build/release/ /opt/rir/external/custom-r "e:PIR-LLVM -R -r --iterations 3"
  retry: 2

deploy:
  stage: Deploy
  except:
    - schedules
  image: docker:stable
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:19.03.0-dind
  before_script:
    - docker info
  variables:
    GIT_STRATEGY: none
  script:
    - echo "$CI_BUILD_TOKEN" | docker login -u "$CI_BUILD_USER" --password-stdin registry.gitlab.com
    - docker pull registry.gitlab.com/rirvm/rir_mirror:$CI_COMMIT_SHA
    - docker tag registry.gitlab.com/rirvm/rir_mirror:$CI_COMMIT_SHA registry.gitlab.com/rirvm/rir_mirror:master
    - docker push registry.gitlab.com/rirvm/rir_mirror:master
    - docker pull registry.gitlab.com/rirvm/rir_mirror/benchmark:$CI_COMMIT_SHA
    - docker tag registry.gitlab.com/rirvm/rir_mirror/benchmark:$CI_COMMIT_SHA registry.gitlab.com/rirvm/rir_mirror/benchmark:master
    - docker push registry.gitlab.com/rirvm/rir_mirror/benchmark:master
  tags:
    - dockerInDocker
  only:
    - master

cleanup_registry:
  stage: Cleanup
  image: ruby:2.5
  before_script: []
  script:
    - echo -n "$CI_BUILD_TOKEN" | ruby container/cleanup.rb

benchmark_llvm:
  image: registry.gitlab.com/rirvm/rir_mirror/benchmark:$CI_COMMIT_SHA
  stage: Benchmark
  needs:
    - test_benchmarks
  variables:
    GIT_STRATEGY: none
  tags:
    - benchmarks
  script:
    - ifconfig
    - $REBENCH_RUN "e:PIR-LLVM $REBENCH_OPTIONS"
  artifacts:
    paths:
    - benchmarks.data
    expire_in: 24 month
  retry: 2

benchmark_gnur:
  image: registry.gitlab.com/rirvm/rir_mirror/benchmark-baseline
  stage: Benchmark
  variables:
    GIT_STRATEGY: none
  only:
    refs:
      - schedules
  tags:
    - benchmarks
  script:
    - $REBENCH_RUN_BL "e:GNU-R $REBENCH_OPTIONS"
  artifacts:
    paths:
    - benchmarks.data
    expire_in: 6 month
benchmark_fastr:
  image: registry.gitlab.com/rirvm/rir_mirror/benchmark-baseline
  stage: Benchmark
  variables:
    GIT_STRATEGY: none
  only:
    refs:
      - schedules
  tags:
    - benchmarks
  script:
    - $REBENCH_RUN_BL "e:FASTR $REBENCH_OPTIONS"
  artifacts:
    paths:
    - benchmarks.data
    expire_in: 6 month
