dist: trusty

language: cpp

os:
  - osx
  - linux

compiler:
  - clang
  - gcc

env:
  - CORES=3 CHECK=check BUILD=release
  - CORES=3 CHECK=check BUILD=debug
  - CHECK=test-all-devel BUILD=release
  - CHECK=check-recommended BUILD=release

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
  exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang
    - os: linux
      env: CORES=3 CHECK=check BUILD=release
    - os: osx
      env: CORES=3 CHECK=check BUILD=debug
    - os: osx
      env: CHECK=test-all-devel BUILD=release
    - os: osx
      env: CHECK=check-recommended BUILD=release

addons:
  apt:
    packages:
      - xdg-utils
      - gfortran
      - subversion
      - make
      - r-base-dev
      - liblzma-dev
      - sed
      - binutils
      - curl
      - cmake
      - rsync
      - xorg-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then . ./tools/ci/before_install-osx.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then . ./tools/ci/before_install-linux.sh; fi

before_script:
  - cmake -DCMAKE_BUILD_TYPE=$BUILD .
  - make setup
  - make -j4

script:
  - ./tools/tests
  - echo "running make $CHECK on a $BUILD build with CORES=$CORES"
  - TEST_MC_CORES=$CORES ./tools/gnur-make-tests $CHECK

cache:
  - ccache
