language: cpp

# Use linux unless specified otherwise
os: linux
dist: trusty

matrix:
  include:

    # macOS clang
    - os: osx
      compiler: clang
      env: CORES=2 CHECK=check BUILD=release

    - os: osx
      compiler: clang
      env: CORES=2 CHECK=check BUILD=release PIR_ENABLE=force

    # linux gcc
    - compiler: g++-7
      env: CHECK=check BUILD=release
      addons: &gcc7
        apt:
          packages: g++-7
          sources:
            - ubuntu-toolchain-r-test

    - compiler: g++-7
      env: CORES=2 CHECK=check BUILD=debug PIR_ENABLE=force
      addons: *gcc7

    - compiler: g++-7
      env: CHECK=test-all-devel BUILD=release PIR_ENABLE=force ENABLE_VALGRIND=1
      addons: *gcc7

    - compiler: g++-7
      env: CHECK=check-recommended BUILD=release
      addons: *gcc7

addons:
  apt:
    packages:
      - xdg-utils
      - gfortran
      - subversion
      - make
      - r-base-dev
      - liblzma-dev
      - sed
      - binutils
      - curl
      - cmake
      - rsync
      - xorg-dev
      - valgrind

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then . ./tools/ci/before_install-osx.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then . ./tools/ci/before_install-linux.sh; fi

before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD ..
  - make setup
  - make -j2

script:
  - ./bin/tests
  - echo "JIT enabled"
  - R_ENABLE_JIT=2 ./bin/tests
  - R_ENABLE_JIT=2 PIR_ENABLE=force ./bin/tests
  - R_ENABLE_JIT=3 ./bin/tests
  - echo "running make $CHECK on a $BUILD build with CORES=$CORES and PIR_ENABLE=$PIR_ENABLE"
  - TEST_MC_CORES=$CORES ./bin/gnur-make-tests $CHECK

cache:
  ccache: true
  directories:
    - external
