dist: trusty

language: cpp

matrix:
  include:
    - os: osx
      compiler: clang
      env: CORES=2 CHECK=check BUILD=release
    - os: osx
      compiler: clang
      env: CORES=2 CHECK=check BUILD=release PIR_ENABLE=force
    - os: linux
      compiler: gcc
      env: CHECK=check BUILD=release
    - os: linux
      compiler: gcc
      env: CORES=2 CHECK=check BUILD=debug PIR_ENABLE=force
    - os: linux
      compiler: gcc
      env: CHECK=test-all-devel BUILD=release PIR_ENABLE=force ENABLE_VALGRIND=1
    - os: linux
      compiler: gcc
      env: CHECK=check-recommended BUILD=release

addons:
  apt:
    packages:
      - xdg-utils
      - gfortran
      - subversion
      - make
      - r-base-dev
      - liblzma-dev
      - sed
      - binutils
      - curl
      - cmake
      - rsync
      - xorg-dev
      - valgrind

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then . ./tools/ci/before_install-osx.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then . ./tools/ci/before_install-linux.sh; fi

before_script:
  - cmake -DCMAKE_BUILD_TYPE=$BUILD .
  - make setup
  - make -j2

script:
  - ./bin/tests
  - echo "JIT enabled"
  - R_ENABLE_JIT=2 ./bin/tests
  - R_ENABLE_JIT=2 PIR_ENABLE=force ./bin/tests
  - R_ENABLE_JIT=3 ./bin/tests
  - echo "running make $CHECK on a $BUILD build with CORES=$CORES and PIR_ENABLE=$PIR_ENABLE"
  - TEST_MC_CORES=$CORES ./bin/gnur-make-tests $CHECK

cache:
  ccache: true
  directories:
  - external

