dist: trusty

language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      compiler: clang
      env: CORES=2 CHECK=check BUILD=release
    - os: linux
      compiler: gcc
      env: CORES=2 CHECK=check BUILD=debug ENABLE_VALGRIND=1
    - os: linux
      compiler: gcc
      env: CHECK=test-all-devel BUILD=release ENABLE_VALGRIND=1
    - os: linux
      compiler: gcc
      env: CHECK=check-recommended BUILD=release

addons:
  apt:
    packages:
      - xdg-utils
      - gfortran
      - subversion
      - make
      - r-base-dev
      - liblzma-dev
      - sed
      - binutils
      - curl
      - cmake
      - rsync
      - xorg-dev
      - valgrind

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then . ./tools/ci/before_install-osx.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then . ./tools/ci/before_install-linux.sh; fi

before_script:
  - cmake -DCMAKE_BUILD_TYPE=$BUILD .
  - make setup
  - make -j2

script:
  - ./tools/tests
  - echo "running make $CHECK on a $BUILD build with CORES=$CORES"
  - TEST_MC_CORES=$CORES ./tools/gnur-make-tests $CHECK

cache:
  - ccache

