#ifndef HANDLER_H
#define HANDLER_H

#include "llvm.h"
#include "RIntlns.h"

namespace rjit {

// this will identify the handler methods. I can in theory get them by their signature, but this is cleaner imho
#define handler public: void dispatch(llvm::BasicBlock * b) override; protected


class Handler {

public:
    /** The dispatcher method. Autogenerated in some other file.
     */
    virtual void dispatch(llvm::BasicBlock * b);

};


class MyHandler: public Handler {



handler:
    void someName();



};


} // namespace rjit

#endif // HANDLER_H

