/*
AUTOMATICALLY GENERATED FILE, DO NOT EDIT. 

This file is automatically generated as part of the rjit build step. Do not edit it directly as all your changes will be lost after a new build cycle. If you want to change which intrinsics are supported, edit the respective files that define them. 
*/

#include "intrinsics.h"

namespace rjit {
namespace ir {


char const * convertToLogicalNoNA::Name = "convertToLogicalNoNA";
llvm::FunctionType * convertToLogicalNoNA::Type = llvm::FunctionType::get(t::Int, { t::SEXP, t::SEXP }, false);

char const * printValue::Name = "printValue";
llvm::FunctionType * printValue::Type = llvm::FunctionType::get(t::Void, { t::SEXP }, false);

char const * startFor::Name = "startFor";
llvm::FunctionType * startFor::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP }, false);

char const * loopSequenceLength::Name = "loopSequenceLength";
llvm::FunctionType * loopSequenceLength::Type = llvm::FunctionType::get(t::Int, { t::SEXP, t::SEXP }, false);

char const * getForLoopValue::Name = "getForLoopValue";
llvm::FunctionType * getForLoopValue::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::Int }, false);

char const * markVisible::Name = "markVisible";
llvm::FunctionType * markVisible::Type = llvm::FunctionType::get(t::Void, {  }, false);

char const * markInvisible::Name = "markInvisible";
llvm::FunctionType * markInvisible::Type = llvm::FunctionType::get(t::Void, {  }, false);

char const * userConstant::Name = "userConstant";
llvm::FunctionType * userConstant::Type = llvm::FunctionType::get(t::Void, { t::SEXP }, false);

char const * genericGetVar::Name = "genericGetVar";
llvm::FunctionType * genericGetVar::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP }, false);

char const * genericGetEllipsisArg::Name = "genericGetEllipsisArg";
llvm::FunctionType * genericGetEllipsisArg::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP }, false);

char const * genericSetVar::Name = "genericSetVar";
llvm::FunctionType * genericSetVar::Type = llvm::FunctionType::get(t::Void, { t::SEXP, t::SEXP, t::SEXP }, false);

char const * genericSetVarParent::Name = "genericSetVarParent";
llvm::FunctionType * genericSetVarParent::Type = llvm::FunctionType::get(t::Void, { t::SEXP, t::SEXP, t::SEXP }, false);

char const * getFunction::Name = "getFunction";
llvm::FunctionType * getFunction::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP }, false);

char const * getGlobalFunction::Name = "getGlobalFunction";
llvm::FunctionType * getGlobalFunction::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP }, false);

char const * getSymFunction::Name = "getSymFunction";
llvm::FunctionType * getSymFunction::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP }, false);

char const * getBuiltinFunction::Name = "getBuiltinFunction";
llvm::FunctionType * getBuiltinFunction::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP }, false);

char const * getInternalBuiltinFunction::Name = "getInternalBuiltinFunction";
llvm::FunctionType * getInternalBuiltinFunction::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP }, false);

char const * checkFunction::Name = "checkFunction";
llvm::FunctionType * checkFunction::Type = llvm::FunctionType::get(t::Void, { t::SEXP }, false);

char const * createPromise::Name = "createPromise";
llvm::FunctionType * createPromise::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP }, false);

char const * sexpType::Name = "sexpType";
llvm::FunctionType * sexpType::Type = llvm::FunctionType::get(t::Int, { t::SEXP }, false);

char const * addArgument::Name = "addArgument";
llvm::FunctionType * addArgument::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP }, false);

char const * addKeywordArgument::Name = "addKeywordArgument";
llvm::FunctionType * addKeywordArgument::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP, t::SEXP }, false);

char const * addEllipsisArgument::Name = "addEllipsisArgument";
llvm::FunctionType * addEllipsisArgument::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP, t::Bool }, false);

char const * callBuiltin::Name = "callBuiltin";
llvm::FunctionType * callBuiltin::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP, t::SEXP, t::SEXP }, false);

char const * callSpecial::Name = "callSpecial";
llvm::FunctionType * callSpecial::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP, t::SEXP, t::SEXP }, false);

char const * callClosure::Name = "callClosure";
llvm::FunctionType * callClosure::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP, t::SEXP, t::SEXP }, false);

char const * createClosure::Name = "createClosure";
llvm::FunctionType * createClosure::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP, t::SEXP }, false);

char const * genericUnaryMinus::Name = "genericUnaryMinus";
llvm::FunctionType * genericUnaryMinus::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP, t::SEXP }, false);

char const * genericUnaryPlus::Name = "genericUnaryPlus";
llvm::FunctionType * genericUnaryPlus::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP, t::SEXP }, false);

char const * genericAdd::Name = "genericAdd";
llvm::FunctionType * genericAdd::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP, t::SEXP, t::SEXP }, false);

char const * genericSub::Name = "genericSub";
llvm::FunctionType * genericSub::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP, t::SEXP, t::SEXP }, false);

char const * genericMul::Name = "genericMul";
llvm::FunctionType * genericMul::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP, t::SEXP, t::SEXP }, false);

char const * genericDiv::Name = "genericDiv";
llvm::FunctionType * genericDiv::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP, t::SEXP, t::SEXP }, false);

char const * genericPow::Name = "genericPow";
llvm::FunctionType * genericPow::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP, t::SEXP, t::SEXP }, false);

char const * genericSqrt::Name = "genericSqrt";
llvm::FunctionType * genericSqrt::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP, t::SEXP }, false);

char const * genericExp::Name = "genericExp";
llvm::FunctionType * genericExp::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP, t::SEXP }, false);

char const * genericEq::Name = "genericEq";
llvm::FunctionType * genericEq::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP, t::SEXP, t::SEXP }, false);

char const * genericNe::Name = "genericNe";
llvm::FunctionType * genericNe::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP, t::SEXP, t::SEXP }, false);

char const * genericLt::Name = "genericLt";
llvm::FunctionType * genericLt::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP, t::SEXP, t::SEXP }, false);

char const * genericLe::Name = "genericLe";
llvm::FunctionType * genericLe::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP, t::SEXP, t::SEXP }, false);

char const * genericGe::Name = "genericGe";
llvm::FunctionType * genericGe::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP, t::SEXP, t::SEXP }, false);

char const * genericGt::Name = "genericGt";
llvm::FunctionType * genericGt::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP, t::SEXP, t::SEXP }, false);

char const * genericBitAnd::Name = "genericBitAnd";
llvm::FunctionType * genericBitAnd::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP, t::SEXP, t::SEXP }, false);

char const * genericBitOr::Name = "genericBitOr";
llvm::FunctionType * genericBitOr::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP, t::SEXP, t::SEXP }, false);

char const * genericNot::Name = "genericNot";
llvm::FunctionType * genericNot::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP, t::SEXP }, false);

char const * genericGetVarMissOK::Name = "genericGetVarMissOK";
llvm::FunctionType * genericGetVarMissOK::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP }, false);

char const * genericGetEllipsisValueMissOK::Name = "genericGetEllipsisValueMissOK";
llvm::FunctionType * genericGetEllipsisValueMissOK::Type = llvm::FunctionType::get(t::SEXP, { t::SEXP, t::SEXP }, false);

char const * checkSwitchControl::Name = "checkSwitchControl";
llvm::FunctionType * checkSwitchControl::Type = llvm::FunctionType::get(t::Void, { t::SEXP, t::SEXP }, false);

char const * switchControlCharacter::Name = "switchControlCharacter";
llvm::FunctionType * switchControlCharacter::Type = llvm::FunctionType::get(t::Int, { t::SEXP, t::SEXP, t::SEXP }, false);

char const * switchControlInteger::Name = "switchControlInteger";
llvm::FunctionType * switchControlInteger::Type = llvm::FunctionType::get(t::Int, { t::SEXP, t::Int }, false);

char const * returnJump::Name = "returnJump";
llvm::FunctionType * returnJump::Type = llvm::FunctionType::get(t::Void, { t::SEXP, t::SEXP }, false);

} // namespace ir
} // namespace rjit

