require("Matrix")
D5. <- Diagonal(x = 5:1)
D5N <- D5.; D5N[5,5] <- NA
f = function() identical(pmin(1, D5.), pmin(1, as.matrix(D5.)))
stopifnot(f())
stopifnot(f())
stopifnot(f())
stopifnot(f())
stopifnot(f())
stopifnot(f())
stopifnot(f())
stopifnot(f())
stopifnot(f())
