require("Matrix")
print(cS. <- contr.SAS(5, sparse = TRUE))
x1 <- x2 <- c('a','b','a','b','c')
print(xtabs(~ x1 + x2, sparse= TRUE, exclude = 'c'))
M <- Matrix(diag(1:10), sparse=TRUE)
as.matrix(pmax(M, 7))
