cc <- function(...)c(...)
setGeneric("cc")
setMethod("cc", "character", function(...)paste(...))
setClassUnion("Number", c("numeric", "complex"))
setMethod("cc", "Number", function(...) sum(...))
stopifnot(identical(cc(1:10, 1+1i), sum(1:10, 1+1i)))
stopifnot(identical(cc(1:10, 1+1i), sum(1:10, 1+1i)))
stopifnot(identical(cc(1:10, 1+1i), sum(1:10, 1+1i)))
stopifnot(identical(cc(1:10, 1+1i), sum(1:10, 1+1i)))
