f <- rir.compile(function(x, y) x + y)
sig <- rir.mkSignature(NoSuperAssign=TRUE, NoReflection=TRUE, type="int$ int$ -> int$")
rir.setSignatureExplicit(f, sig)
f(1L, 2L)
f(3L, 4L)
f(5L, 6L)
f(7L, 8L)
stopifnot(rir.signature(f) == sig)
# TODO: Implement these assertions
# stopifnot(tryCatch({ f(9, 10L); FALSE }, error=function(err) TRUE)) 
x <- 1
rir.setSignature(f, NoSuperAssign=TRUE)
# stopifnot(tryCatch({ f({ x <<- 2; 11L }, 12L); FALSE }, error=function(err) TRUE))
rir.setSignature(f, NoReflection=TRUE)
# stopifnot(tryCatch({ f({ parent.frame(); 13L }, 14L); FALSE }, error=function(err) TRUE))
rir.setSignature(f)
f(15, 16)
rir.setSignature(f, NoSuperAssign=TRUE, NoReflection=TRUE, type="int$ int$ -> int$")
stopifnot(rir.signature(f) == sig)
