#!/bin/bash

SCRIPTPATH=`cd $(dirname "$0") && pwd`
ROOT="$SCRIPTPATH/.."
SRC="$ROOT/rir/src/"

. "${SCRIPTPATH}/script_include.sh"

trap 'echo "   skipping" && exit 0' INT

cppcheck --version
cppcheck -q -j `ncores` --inline-suppr -I $SRC --suppressions-list=$ROOT/.cppcheck_suppressions --enable=portability,warning,performance,style --suppress=unusedLabel:$SRC/interpreter/interp.cpp --suppress=unusedStructMember:$SRC/interpreter/interp.cpp $SRC --suppress=cstyleCast --error-exitcode=2 "$@"
