#!/bin/sh

SCRIPTPATH=`cd $(dirname "$0") && pwd`

R_HOME=`cat .R_HOME`
CHK=$1
LIBRARY_DIR=`pwd`

PKG="$SCRIPTPATH/../rir/"

export EXTRA_LOAD_SO="`ls $LIBRARY_DIR/librir.*`"
export EXTRA_LOAD_R="$PKG/R/rir.R"
export R_ENABLE_JIT=2

cd $R_HOME
git clean -fx -e Makefile tests/

cd tests
make $CHK
