#!/bin/sh

set -e

TYPE=$1

SCRIPTPATH=`cd $(dirname "$0") && pwd`
if [ ! -d $SCRIPTPATH ]; then
    echo "Could not determine absolute dir of $0"
    echo "Maybe accessed with symlink"
fi

# Run install script to deploy new hooks
$SCRIPTPATH/install_hooks.sh

. "${SCRIPTPATH}/../.local.config"

HOOKS_PATH="${SCRIPTPATH}/${TYPE}.d"

echo "# running $TYPE hooks in tools/${TYPE}.d"
echo "#   please do not skip them on public branches"
echo "################################################"
echo ""

for script in `ls -v ${HOOKS_PATH}/*.hook`; do
    name=`basename $script | sed 's/[0-9][0-9]-//'`
    echo "-> running $name"
    $script $ROOT_DIR $BUILD_DIR
    echo ""
done
