#!/bin/sh

set -e

TYPE=$1


SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

# Run install script to deploy new hooks
$SCRIPTPATH/install_hooks.sh

ROOT_DIR=`cd $SCRIPTPATH/../ && pwd`
BUILD_DIR=`grep rjit_BINARY_DIR $ROOT_DIR/CMakeCache.txt | sed 's/rjit_BINARY_DIR:STATIC=//'`

HOOKS_PATH="${SCRIPTPATH}/${TYPE}.d"

echo "# running $TYPE hooks in tools/${TYPE}.d"
echo "#   please do not skip them on public branches"
echo "################################################"
echo ""

for script in `ls -v $HOOKS_PATH`; do
    name=`echo $script | sed 's/[0-9][0-9]-//'`
    echo "-> running $name"
    $HOOKS_PATH/$script $ROOT_DIR $BUILD_DIR
    echo ""
done
