#!/bin/bash

ROOT_DIR=$1
R_HOME=$2
BUILD_DIR=`pwd`

echo $R_HOME > .R_HOME

if [ $ROOT_DIR != $BUILD_DIR ]; then
    if [ ! -f .gdbinit ]; then
        ln -s $ROOT_DIR/.gdbinit
        ln -s $ROOT_DIR/tools/pirpp.py .pirpp.py
    fi
fi
