#!/bin/sh

ROOT_DIR=$1
R_HOME=$2

echo $R_HOME > .R_HOME

if [ ! -f .gdbinit ]; then
    ln -s $ROOT_DIR/.gdbinit
fi
if [ ! -f tests ]; then
    echo "#!/bin/sh\n$ROOT_DIR/tools/tests" > ./tests
    chmod +x ./tests
fi
